feat: Stable Release
pentagonxyz/huffmate pull request #44
Opened 2022-09-09 19:34 UTC by abigger87

## Overview

This PR will release the first stable version of huffmate!

### Checklist

- [ ] ERC1155
- [ ] ERC721
- [ ] ERC20

### Changelog

...

2022-09-13 16:51 UTC, kadenzipfel commented
started working on erc721 again! will be done asap

2022-09-15 22:11 UTC, kadenzipfel requested changes

2022-09-16 00:27 UTC, kadenzipfel commented on src/tokens/ERC20.huff
> +#define macro MAIN_ERC20() = takes (1) returns (1) {
noticed this in a few other places as well. tbh both strategies are good but i think important to maintain consistency throughout the repo by defining which style we prefer

2022-09-18 10:47 UTC, Philogy commented
I propose adding the shuffle macro I've written to mechanisms for V1: https://github.com/Philogy/erc721h/blob/main/src/utils/Mechs.huff

2022-09-19 15:09 UTC, abigger87 commented
> I propose adding the shuffle macro I've written to mechanisms for V1: https://github.com/Philogy/erc721h/blob/main/src/utils/Mechs.huff

Very cool, will add. Thanks!

2022-09-23 13:47 UTC, merged